### ISSUE TITLE
Hemsida nere

### ISSUE THREAD

**Issue by sermuns** [williamtorberntsson/openliunet#13]
https://liunet.eu/ finns inte längre. Har domänen löpt ut? Finns hemsidan på någon alternativ adress?

**Comment by williamtorberntsson** [comment]
Hej!

Jag glömde uppdatera mina betalningsuppgifter så dömänen löpte ur utan att jag visste om det. Om jag vill få tillbaka domänen var jag tvungen att betala 763 SEK vilket är en återköpsavgift som jag måste betala p.g.a. att det är en .eu domän. Det tänker jag inte betala. Domänen kommer kommer komma upp på en auktion om några dagar och då hoppas jag kunna köpa tillbaka den billigt. Jag tror domänen kommer dyga upp här: https://se.auctions.godaddy.com/

Om ni har bra förslag på andra billiga domännamn är jag på. Dock kul om jag får ha kvar domänen då den fick 150 besök från google förra månaden.

**Comment by williamtorberntsson** [comment]
Den finns nu på openliunet.eu istället.
