### ISSUE TITLE
LiU.se:s nyhetsflöde

### ISSUE THREAD

**Issue by HugoNikanor** [williamtorberntsson/openliunet#2]
LiU:s nyheter finns som ett öppet RSS-flöde. Kan möjligen vara till intresse

https://liu-news-rss.kubernetes-public.it.liu.se/

**Comment by williamtorberntsson** [comment]
Det kan vara intressant :+1: . Men jag antar att det inte ligger dolt bakom liunet? Då tillhör det nog inte det här repot

**Comment by HugoNikanor** [comment]
Det gör det inte. Fick informationen om flödet från en LiU-IT-anställd.
